### ISSUE TITLE
NoClassDefFoundError when upgrading from 3.3.3 to 3.4.x

### ISSUE THREAD

**Issue by jorgebsa** [quarkiverse/quarkus-jgit#184]
Hi @gastaldi ,

Renovate bot picked the `3.4.0` and `3.4.1` upgrades for a couple projects I work on using this extension. In both cases, the simple bump in version to 3.4.x resulted in failing tests with `java.lang.NoClassDefFoundError`. 

I've upgraded the from Quarkus `3.19` to `3.21`, but nothing's changed. Today, both projects are running on Quarkus `3.21.1`, Java `21` and JVM mode (never used native). For now, I've had to keep them with `3.3.3`

```
[ERROR]   UpdateServiceInstanceTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.jgit.deployment.JGitProcessor#reflection threw an exception: java.lang.NoClassDefFoundError: org/eclipse/jgit/lib/CoreConfig$TrustStat
	at io.quarkus.jgit.deployment.JGitProcessor.reflection(JGitProcessor.java:43)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1591)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.lib.CoreConfig$TrustStat
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:569)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
	... 10 more
```

I didn't notice on release notes of `3.4.0` the removal of anything, but indeed there were some upgrades related to `jgit` and `jsch` that potentially could cause this issue.

Have you faced this one at all? If so, have you had to add/update any other dependency to make it work?

**Comment by jorgebsa** [comment]
@gastaldi as soon as I created this, I saw the two closed issues that duplicate this. My bad :)
